import React,{useMemo,useRef,useState} from "react";
import {Upload,Loader2,AlertTriangle,CheckCircle2,Download,Users,CalendarClock,HeartPulse,Database,FileSpreadsheet,ShieldAlert,Search} from "lucide-react";

const SERVICE_LABELS={hivTest:"HIV testing",art:"ART / ARV",tb:"TB",pep:"PEP",tpt:"TPT",condoms:"Condoms",lubricant:"Lubricants",nsp:"NSP",hepb:"Hepatitis B",hepc:"Hepatitis C",sti:"STI",prep:"PrEP",cancer:"Cervical / anal cancer",fp:"Family planning",mental:"Mental health",substance:"Alcohol / substance",violence:"Violence / GBV"};
const DIM_LABELS={typology:"Typology",sex:"Sex",county:"County",subcounty:"Sub-county",ward:"Ward",hotspot:"Hotspot",sr:"SR",pe:"Peer educator",status:"Programme status",hivEnrollment:"HIV status at enrollment",artStatus:"ART status",pregnancy:"Pregnancy",mmd:"MMD",viral:"Viral level"};
const css=`*{box-sizing:border-box}body{margin:0;font-family:Inter,Segoe UI,Arial,sans-serif;background:#f5f7fb;color:#14213d}.app{min-height:100vh}.top{background:linear-gradient(135deg,#0f1f3d,#19386b);color:#fff;padding:30px 34px}.top h1{margin:0 0 6px;font-size:30px}.top p{margin:0;opacity:.82}.wrap{max-width:1450px;margin:auto;padding:26px}.upload{background:#fff;border:2px dashed #b8c5d9;border-radius:18px;padding:50px;text-align:center;cursor:pointer;box-shadow:0 8px 30px #17233a12}.upload:hover{border-color:#3b67a8}.hidden{display:none}.status{margin-top:18px;background:#eef4ff;border-radius:12px;padding:14px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.card{background:#fff;border-radius:16px;padding:20px;box-shadow:0 5px 22px #17233a0c;border:1px solid #e5eaf2}.kpi{font-size:30px;font-weight:800;margin-top:8px}.muted{color:#68758a;font-size:13px}.section{margin-top:24px}.section h2{font-size:20px;margin:0 0 14px}.tabs{display:flex;gap:8px;overflow:auto;margin:18px 0}.tab{border:1px solid #d9e0eb;background:#fff;padding:9px 14px;border-radius:9px;cursor:pointer;white-space:nowrap}.tab.active{background:#0f1f3d;color:#fff}.bars{display:grid;gap:10px}.barrow{display:grid;grid-template-columns:190px 1fr 80px;align-items:center;gap:10px}.bar{height:12px;background:#e7ecf3;border-radius:20px;overflow:hidden}.fill{height:100%;background:#3973c9;border-radius:20px}.tablewrap{overflow:auto;max-height:520px;border:1px solid #e2e7ef;border-radius:12px}.table{width:100%;border-collapse:collapse;font-size:13px}.table th,.table td{padding:10px;border-bottom:1px solid #edf0f5;text-align:left;white-space:nowrap}.table th{position:sticky;top:0;background:#f8fafc}.pill{display:inline-block;padding:4px 8px;border-radius:20px;background:#eef3fb}.danger{background:#fff0f0;color:#b42318}.warn{background:#fff7e6;color:#9a6700}.good{background:#edf9f0;color:#177245}.actions{display:flex;gap:10px;flex-wrap:wrap}.btn{border:0;border-radius:9px;padding:10px 15px;cursor:pointer;background:#0f1f3d;color:#fff}.btn.secondary{background:#e9eef6;color:#17243c}.error{color:#b42318;background:#fff1f1;padding:14px;border-radius:10px}.search{width:100%;padding:11px 14px;border:1px solid #d7deea;border-radius:9px;margin-bottom:12px}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}.barrow{grid-template-columns:120px 1fr 60px}}`;

export default function App(){
 const [result,setResult]=useState(null),[insights,setInsights]=useState([]),[status,setStatus]=useState("Ready"),[error,setError]=useState(""),[sheet,setSheet]=useState(0),[query,setQuery]=useState("");
 const workerRef=useRef(null);const fileRef=useRef(null);
 const run=file=>{if(!file)return;setResult(null);setInsights([]);setError("");setStatus(`Preparing ${file.name}…`);const reader=new FileReader();reader.onload=()=>{const w=new Worker(new URL("./analyzerWorker.js",import.meta.url),{type:"module"});workerRef.current=w;w.onmessage=e=>{if(e.data.type==="status")setStatus(e.data.message);else if(e.data.type==="done"){setResult(e.data.result);setInsights(e.data.insights||[]);setStatus("Analysis complete");w.terminate();workerRef.current=null}else{setError(e.data.message);setStatus("Analysis failed");w.terminate();workerRef.current=null}};w.postMessage(reader.result,[reader.result])};reader.onerror=()=>{setError("The browser could not read this file.");setStatus("Failed");};reader.readAsArrayBuffer(file)};
 const cancel=()=>{workerRef.current?.terminate();workerRef.current=null;setStatus("Stopped");};
 const exportJSON=()=>{if(!result)return;const blob=new Blob([JSON.stringify(result,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="data-insight-studio-analysis.json";a.click();URL.revokeObjectURL(a.href)};
 const current=result?.sheets?.[sheet];
 const filteredDue=useMemo(()=>{const q=query.toLowerCase().trim();return (result?.cohort?.due||[]).filter(x=>!q||[x.name,x.id,x.typology,x.pe,x.sr,x.status,x.kind].join(" ").toLowerCase().includes(q)).slice(0,500)},[result,query]);
 return <><style>{css}</style><div className="app"><div className="top"><h1>Data Insight Studio</h1><p>Cohort intelligence • M&E analysis • service coverage • action lists</p></div><div className="wrap">
 {!result&&<><div className="upload" onClick={()=>fileRef.current?.click()}><Upload size={42}/><h2>Upload the cohort register</h2><p>Large Excel workbooks are processed in a background worker so the page stays responsive.</p><input ref={fileRef} className="hidden" type="file" accept=".xlsx,.xls,.xlsm" onChange={e=>run(e.target.files?.[0])}/></div><div className="status"><Loader2 size={16} style={{verticalAlign:"middle",marginRight:7}} className={status.includes("…")?"spin":""}/>{status}</div>{error&&<div className="error" style={{marginTop:14}}>{error}</div>}</>}
 {result&&<>
 <div className="actions"><button className="btn secondary" onClick={()=>{setResult(null);setStatus("Ready")}}>Analyze another workbook</button><button className="btn" onClick={exportJSON}><Download size={15}/> Export analysis JSON</button><button className="btn secondary" onClick={cancel}>Stop</button></div>
 <div className="grid section"><div className="card"><Database size={19}/><div className="kpi">{result.sheetCount}</div><div className="muted">Sheets analyzed</div></div><div className="card"><Users size={19}/><div className="kpi">{result.cohort?.recordCount??0}</div><div className="muted">Cohort records</div></div><div className="card"><FileSpreadsheet size={19}/><div className="kpi">{result.totalColumns.toLocaleString()}</div><div className="muted">Columns scanned</div></div><div className="card"><CalendarClock size={19}/><div className="kpi">{result.cohort?.due?.length??0}</div><div className="muted">Due / overdue actions</div></div></div>
 {insights.length>0&&<div className="card section"><h2>Automatic intelligence</h2>{insights.map((x,i)=><p key={i}>• {x}</p>)}</div>}
 <div className="section"><h2>Workbook sheets</h2><div className="tabs">{result.sheets.map((x,i)=><button key={x.name} className={`tab ${i===sheet?"active":""}`} onClick={()=>setSheet(i)}>{x.name} · {x.rows.toLocaleString()}</button>)}</div></div>
 {current&&<div className="grid"><div className="card"><b>{current.name}</b><div className="muted">{current.rows.toLocaleString()} data rows · {current.columns.toLocaleString()} columns</div></div><div className="card"><b>Header row</b><div className="kpi" style={{fontSize:24}}>{current.headerRow}</div></div><div className="card"><b>Formula/error cells</b><div className="kpi" style={{fontSize:24}}>{current.quality?.formulaErrors??0}</div></div><div className="card"><b>Duplicate IDs</b><div className="kpi" style={{fontSize:24}}>{current.quality?.duplicateRows??0}</div></div></div>}
 {result.cohort&&<>
 <div className="card section"><h2><HeartPulse size={20}/> Service coverage</h2><div className="bars">{Object.entries(result.cohort.coverage||{}).map(([k,x])=><div className="barrow" key={k}><span>{SERVICE_LABELS[k]||k}</span><div className="bar"><div className="fill" style={{width:`${Math.min(100,x.pct||0)}%`}}/></div><b>{(x.pct||0).toFixed(1)}%</b></div>)}</div></div>
 <div className="grid section"><div className="card"><b>HIV testing</b><div className="kpi">{result.cohort.hiv.tested}</div><div className="muted">{result.cohort.hiv.positivityPct.toFixed(1)}% positivity · {result.cohort.hiv.positive} positive</div></div><div className="card"><b>Programme statuses</b>{Object.entries(result.cohort.programmeStatuses||{}).slice(0,8).map(([k,v])=><p key={k}><span className="pill">{k}</span> {v}</p>)}</div><div className="card"><b>Age groups</b>{Object.entries(result.cohort.ageGroups||{}).map(([k,v])=><p key={k}>{k}: <b>{v}</b></p>)}</div><div className="card"><b>Detected roles</b><div className="muted">{Object.entries(result.cohort.roles||{}).filter(([,v])=>v.length).map(([k,v])=><div key={k} style={{marginTop:5}}>{k}: {v.length}</div>)}</div></div></div>
 <div className="section"><h2>ARV / appointment action list</h2><div className="card"><Search size={16} style={{verticalAlign:"middle"}}/><input className="search" placeholder="Search name, ID, typology, PE, SR…" value={query} onChange={e=>setQuery(e.target.value)}/>{filteredDue.length===0?<p className="muted">No matching due/overdue records.</p>:<div className="tablewrap"><table className="table"><thead><tr><th>Client / record</th><th>Date</th><th>Status</th><th>Type</th><th>Typology</th><th>PE</th><th>SR</th></tr></thead><tbody>{filteredDue.map((x,i)=><tr key={i}><td>{x.name||"—"}</td><td>{x.date}</td><td><span className={`pill ${x.status==="Overdue"?"danger":x.status==="Due today"?"warn":"good"}`}>{x.status}</span></td><td>{x.kind}</td><td>{x.typology||"—"}</td><td>{x.pe||"—"}</td><td>{x.sr||"—"}</td></tr>)}</tbody></table></div>}</div></div>
 <div className="grid section">{Object.entries(result.cohort.dimensions||{}).slice(0,8).map(([k,vals])=><div className="card" key={k}><h3>{DIM_LABELS[k]||k}</h3>{vals.slice(0,10).map(v=><p key={v.value}><b>{v.value}</b> <span className="muted">{v.count}</span></p>)}</div>)}</div></>}
 <div className="card section"><h2>Field inventory — everything scanned</h2><div className="tablewrap"><table className="table"><thead><tr><th>Field</th><th>Type</th><th>Filled</th><th>Missing</th><th>Unique</th><th>Errors</th></tr></thead><tbody>{current?.fields?.filter(f=>!query||f.name.toLowerCase().includes(query.toLowerCase())).map((f,i)=><tr key={i}><td>{f.name}</td><td>{f.type}</td><td>{f.nonEmpty.toLocaleString()}</td><td>{f.missing.toLocaleString()} ({f.missingPct.toFixed(1)}%)</td><td>{f.unique.toLocaleString()}</td><td>{f.errorCount}</td></tr>)}</tbody></table></div></div>
 </>}
 </div></div></>}
