import * as XLSX from "xlsx";
const NULLS=new Set(["","n/a","na","n.a.","null","none","-","—","not applicable"]),ERROR_RE=/#REF!|#DIV\/0!|#VALUE!|#NAME\?|#N\/A|#NUM!|#NULL!/i;
const KEYWORDS=["name","date","age","sex","gender","status","outcome","county","ward","facility","site","month","year","target","result","unique","identifier","code","service","hiv","art","arv","tb","prep","pep","sti","screen","received","provided","started","completed","client","kp","vp","fsw","msm","appointment","refill","regimen","viral"];
const s=v=>v==null?"":v instanceof Date?v.toISOString().slice(0,10):typeof v==="object"?(v.result!==undefined?s(v.result):v.text!==undefined?s(v.text):String(v)):String(v).replace(/\s+/g," ").trim(),norm=v=>s(v).toLowerCase().replace(/[’']/g,"'").replace(/\s+/g," ").trim(),blank=v=>v==null||NULLS.has(norm(v));
const num=v=>{if(typeof v==="number"&&Number.isFinite(v))return v;if(typeof v!=="string")return null;const n=Number(v.replace(/,/g,"").replace(/%/g,"").trim());return Number.isFinite(n)?n:null};
function date(v){if(v instanceof Date&&!Number.isNaN(v.getTime()))return v;if(typeof v==="number"&&v>20000&&v<60000){const d=XLSX.SSF.parse_date_code(v);return d?new Date(Date.UTC(d.y,d.m-1,d.d)):null}if(typeof v!=="string")return null;const p=v.trim().split(/[\/-]/).map(Number);if(p.length!==3||p.some(Number.isNaN))return null;const d=p[0]>31?new Date(Date.UTC(p[0],p[1]-1,p[2])):new Date(Date.UTC(p[2]<100?2000+p[2]:p[2],p[1]-1,p[0]));return Number.isNaN(d.getTime())?null:d}
const iso=d=>d instanceof Date&&!Number.isNaN(d.getTime())?d.toISOString().slice(0,10):null;
function headerRow(g){let best=0,score=-1e9;for(let r=0;r<Math.min(25,g.length);r++){const a=(g[r]||[]).map(s).filter(Boolean),hits=a.reduce((n,x)=>n+(KEYWORDS.some(k=>x.toLowerCase().includes(k))?1:0),0),sc=a.length*2+hits*5+new Set(a.map(x=>x.toLowerCase())).size*.5-r*.1;if(sc>score){score=sc;best=r}}return best}
function headers(g,r,w){const used=new Map();return Array.from({length:w},(_,c)=>{const cur=s(g[r]?.[c]),up=s(g[r-1]?.[c]),up2=s(g[r-2]?.[c]);let parts=[];if(up2&&!/^\d+$/.test(up2))parts.push(up2);if(up&&up!==up2&&!/^\d+$/.test(up))parts.push(up);if(cur)parts.push(cur);const v=parts.length?parts.join(" :: "):`Column ${c+1}`,n=used.get(v)||0;used.set(v,n+1);return n?`${v} (${n+1})`:v})}
function top(map,n=15){return [...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,n).map(([value,count])=>({value,count}))}
function statsFor(g,hr,hs,w){const a=hs.map((name,index)=>({index,name,nonEmpty:0,missing:0,numeric:0,dates:0,text:0,errors:0,sum:0,min:null,max:null,unique:new Set(),freq:new Map()}));let rows=[];for(let r=hr+1;r<g.length;r++){const row=g[r]||[];let has=false;for(let c=0;c<w;c++){const v=row[c],st=a[c];if(!blank(v))has=true;if(blank(v)){st.missing++;continue}st.nonEmpty++;const x=s(v);if(ERROR_RE.test(x))st.errors++;if(st.unique.size<50000)st.unique.add(x);if(st.freq.size<5000)st.freq.set(x,(st.freq.get(x)||0)+1);const n=num(v),d=date(v);if(n!==null&&!(/[\/-]/.test(x)&&typeof v==="string")){st.numeric++;st.sum+=n;st.min=st.min===null?n:Math.min(st.min,n);st.max=st.max===null?n:Math.max(st.max,n)}else if(d){st.dates++;st.min=st.min===null?d:st.min<d?st.min:d;st.max=st.max===null?d:st.max>d?st.max:d}else st.text++}if(has)rows.push(row)}return{rows,fields:a.map(st=>{const type=!st.nonEmpty?"empty":st.dates/st.nonEmpty>.8?"date":st.numeric/st.nonEmpty>.8?"numeric":st.unique.size/Math.max(1,st.nonEmpty)<=.65?"category":"text";return{index:st.index,name:st.name,type,nonEmpty:st.nonEmpty,missing:st.missing,missingPct:rows.length?st.missing/rows.length*100:0,unique:st.unique.size,errorCount:st.errors,sum:st.numeric?st.sum:null,average:st.numeric?st.sum/st.numeric:null,min:st.min instanceof Date?iso(st.min):st.min,max:st.max instanceof Date?iso(st.max):st.max,topValues:top(st.freq)}})} }
function cross(rows,fields){const out=[],cats=fields.filter(f=>f.type==="category").slice(0,14);for(let i=0;i<cats.length;i++)for(let j=i+1;j<cats.length;j++){const a=cats[i],b=cats[j],map=new Map();for(const row of rows){const av=s(row[a.index]),bv=s(row[b.index]);if(!av||!bv)continue;const k=`${av}|||${bv}`;map.set(k,(map.get(k)||0)+1)}const pairs=[...map.entries()].sort((x,y)=>y[1]-x[1]).slice(0,15).map(([k,count])=>{const [x,y]=k.split("|||");return{x,y,count}});if(pairs.length)out.push({x:a.name,y:b.name,pairs})}return out.slice(0,15)}
function numericRelations(rows,fields){const nums=fields.filter(f=>f.type==="numeric").slice(0,20),rel=[];for(let i=0;i<nums.length;i++)for(let j=i+1;j<nums.length;j++){let xs=[],ys=[];for(const r of rows){const x=num(r[nums[i].index]),y=num(r[nums[j].index]);if(x!==null&&y!==null){xs.push(x);ys.push(y)}}if(xs.length<3)continue;const ax=xs.reduce((a,b)=>a+b,0)/xs.length,ay=ys.reduce((a,b)=>a+b,0)/xs.length;let xy=0,xx=0,yy=0;for(let k=0;k<xs.length;k++){const dx=xs[k]-ax,dy=ys[k]-ay;xy+=dx*dy;xx+=dx*dx;yy+=dy*dy}const r=xx&&yy?xy/Math.sqrt(xx*yy):0;if(Math.abs(r)>=.45)rel.push({x:nums[i].name,y:nums[j].name,correlation:Number(r.toFixed(3)),n:xs.length})}return rel.sort((a,b)=>Math.abs(b.correlation)-Math.abs(a.correlation)).slice(0,12)}
function quality(rows,fields){const seen=new Set(),duplicates=new Set();for(const r of rows){const k=JSON.stringify(r);if(seen.has(k))duplicates.add(k);seen.add(k)}const outliers=[];for(const f of fields.filter(x=>x.type==="numeric")){const vals=rows.map(r=>num(r[f.index])).filter(x=>x!==null).sort((a,b)=>a-b);if(vals.length<8)continue;const q1=vals[Math.floor(vals.length*.25)],q3=vals[Math.floor(vals.length*.75)],iqr=q3-q1,lo=q1-1.5*iqr,hi=q3+1.5*iqr,count=vals.filter(v=>v<lo||v>hi).length;if(count)outliers.push({field:f.name,count,lower:lo,upper:hi})}return{duplicateRows:duplicates.size,outliers:outliers.sort((a,b)=>b.count-a.count).slice(0,15)}}
const ROLE_RULES={
 id:[/unique identifier|unique id|identifier code|unique.*code|\buic\b|nupi|ccc number|client id/],
 name:[/kp.*name|vp.*name|client.*name|participant.*name|beneficiary.*name/],
 typology:[/key.*population|vulnerable.*population|typology|\bkp\/vp\b/],sex:[/^sex\b|gender/],age:[/^age\b|age \(/],county:[/county/],subcounty:[/sub.?county/],ward:[/ward/],hotspot:[/hotspot/],sr:[/^sr name|service recipient|sub recipient/],pe:[/peer educator|\bpe name/],
 enrollmentDate:[/date of enrolment|date of enrollment|enrolment date|enrollment date|first contact/],hivEnrollment:[/hiv status.*enrol|hiv status at enrollment|status at enrollment/],appointment:[/next appointment|appointment date|next.*visit|return date|date.*return/],artRefill:[/art.*refill|arv.*refill|refill.*art|refill.*arv|next.*arv|arv.*due|art.*due/],artStatus:[/art status|on art|art outcome|current art|hiv care status/],
 hivTest:[/tested.*hiv|hiv.*test|hts.*result|hiv result|test result/],art:[/\bart\b|antiretroviral|arv/],tb:[/\btb\b|tuberculosis/],pep:[/\bpep\b/],tpt:[/\btpt\b|tb preventive/],condoms:[/condom/],lubricant:[/lubricant/],nsp:[/\bnsp\b|needle|syringe/],hepb:[/hepatitis ?b|\bhep b\b/],hepc:[/hepatitis ?c|\bhep c\b/],sti:[/\bsti\b|sexually transmitted/],prep:[/\bprep\b/],cancer:[/cervical cancer|anal cancer|cervical.*screen|anal.*screen/],fp:[/family planning|\bfp\b|contraceptive/],mental:[/mental health|psychosocial|\bmh\b/],substance:[/alcohol|drug.*screen|substance/],violence:[/violence|gbv|gender based/],pregnancy:[/pregnan/],status:[/programme status|program status|client status|subsequent visit status/],mmd:[/mmd|multi.?month dispensing/],viral:[/viral load|viral level/]
};
function roleFor(name){const n=norm(name);for(const [role,patterns] of Object.entries(ROLE_RULES))if(patterns.some(p=>p.test(n)))return role;return null}
function findRole(fields,role){return fields.filter(f=>roleFor(f.name)===role).sort((a,b)=>a.index-b.index)}
function valueAt(row,fields,role){const f=findRole(fields,role)[0];return f?s(row[f.index]):""}
function uniqueValue(row,fields,role){const f=findRole(fields,role)[0];return f?s(row[f.index]):""}
function positive(v){const x=norm(v);return /^(yes|y|positive|pos|reactive|detected|started|on art|active|provided|received|completed|linked|new|current|taking|dispensed)$/.test(x)||/positive|reactive|detected|on art|started/.test(x)}
function negative(v){const x=norm(v);return /^(no|n|negative|neg|non.?reactive|not done|not received|not provided|not started|no service)$/.test(x)}
function isNA(v){return NULLS.has(norm(v))||/^not applicable$/i.test(s(v))}
function serviceState(row,fields,role){const vals=findRole(fields,role).map(f=>s(row[f.index])).filter(v=>!blank(v));if(!vals.length)return"not_recorded";if(vals.some(positive))return"positive";if(vals.some(negative))return"negative";return"recorded"}
function cohortMetrics(rows,fields){
 const count=rows.length,dims={};["typology","sex","county","subcounty","ward","hotspot","sr","pe","status","hivEnrollment","artStatus","pregnancy","mmd","viral"].forEach(role=>{const map=new Map();for(const r of rows){const v=uniqueValue(r,fields,role);if(v&&!isNA(v))map.set(v,(map.get(v)||0)+1)}dims[role]=top(map,20)});
 const services=["hivTest","art","tb","pep","tpt","condoms","lubricant","nsp","hepb","hepc","sti","prep","cancer","fp","mental","substance","violence"],coverage={};for(const role of services){const vals=rows.map(r=>serviceState(r,fields,role));coverage[role]={denominator:count,done:vals.filter(x=>x==="positive"||x==="recorded").length,notDone:vals.filter(x=>x==="negative").length,notRecorded:vals.filter(x=>x==="not_recorded").length};coverage[role].pct=count?coverage[role].done/count*100:0}
 const hivVals=rows.map(r=>norm(valueAt(r,fields,"hivTest"))).filter(Boolean),hivPos=hivVals.filter(x=>/positive|reactive|detected/.test(x)).length,hivNeg=hivVals.filter(x=>/negative|non.?reactive/.test(x)).length,tested=hivPos+hivNeg;
 const now=new Date();now.setHours(0,0,0,0);const due=[],appointmentFields=findRole(fields,"appointment"),refillFields=findRole(fields,"artRefill");
 for(let i=0;i<rows.length;i++){const row=rows[i],name=uniqueValue(row,fields,"name")||`Record ${i+1}`,id=uniqueValue(row,fields,"id"),artState=serviceState(row,fields,"art");let best=null,kind="";for(const f of refillFields){const d=date(row[f.index]);if(d&&(!best||d>best)){best=d;kind="ARV/ART refill"}}for(const f of appointmentFields){const d=date(row[f.index]);if(d&&(!best||d>best)){best=d;kind=refillFields.length?"ART/ARV follow-up":"Next appointment"}}if(best){const days=Math.round((best-now)/86400000);if(days<=30)due.push({name,id,date:iso(best),days,kind,status:days<0?"Overdue":days===0?"Due today":"Due soon",typology:uniqueValue(row,fields,"typology"),pe:uniqueValue(row,fields,"pe"),sr:uniqueValue(row,fields,"sr"),artStatus:uniqueValue(row,fields,"artStatus"),artRecorded:artState!=="not_recorded"})}}
 due.sort((a,b)=>a.days-b.days);const programmeStatuses={};for(const r of rows){const v=uniqueValue(r,fields,"status");if(v&&!isNA(v))programmeStatuses[v]=(programmeStatuses[v]||0)+1}
 const ageField=findRole(fields,"age")[0],ageGroups={"<18":0,"18–24":0,"25–34":0,"35–44":0,"45+":0};if(ageField)for(const r of rows){const a=num(r[ageField.index]);if(a===null)continue;if(a<18)ageGroups["<18"]++;else if(a<25)ageGroups["18–24"]++;else if(a<35)ageGroups["25–34"]++;else if(a<45)ageGroups["35–44"]++;else ageGroups["45+"]++}
 return{recordCount:count,identifierField:findRole(fields,"id")[0]?.name||null,nameField:findRole(fields,"name")[0]?.name||null,dimensions:dims,ageGroups,coverage,hiv:{tested,testedPct:count?tested/count*100:0,positive:hivPos,negative:hivNeg,positivityPct:tested?hivPos/tested*100:0},due,programmeStatuses,roles:Object.fromEntries(Object.keys(ROLE_RULES).map(k=>[k,findRole(fields,k).map(f=>f.name)]))}
}
function analyzeSheet(name,sheet){const ref=sheet["!ref"];if(!ref)return{name,rows:0,columns:0,headerRow:0,rowCount:0,fields:[],formulaCount:0,formulaErrors:0,analytics:{}};const g=XLSX.utils.sheet_to_json(sheet,{header:1,defval:null,raw:true,blankrows:false}),w=XLSX.utils.decode_range(ref).e.c+1,hr=headerRow(g),hs=headers(g,hr,w),r=statsFor(g,hr,hs,w),rows=r.rows,fields=r.fields;let formulas=0,formulaErrors=0;const range=XLSX.utils.decode_range(ref);for(let rr=range.s.r;rr<=range.e.r;rr++)for(let c=range.s.c;c<=range.e.c;c++){const cell=sheet[XLSX.utils.encode_cell({r:rr,c})];if(cell?.f)formulas++;if(ERROR_RE.test(String(cell?.v??"")))formulaErrors++}const cat=fields.filter(f=>f.type==="category"),numeric=fields.filter(f=>f.type==="numeric"),dates=fields.filter(f=>f.type==="date"),isRef=/^(list|sheet3|srname)$/i.test(name);const insights=[];if(cat[0]?.topValues[0])insights.push(`${cat[0].topValues[0].value} is the largest ${cat[0].name} group (${cat[0].topValues[0].count}).`);if(numeric[0])insights.push(`${numeric[0].name} totals ${numeric[0].sum} across ${numeric[0].nonEmpty} populated values.`);const miss=fields.filter(f=>f.missing>0).sort((a,b)=>b.missingPct-a.missingPct)[0];if(miss)insights.push(`${miss.name} has ${miss.missingPct.toFixed(1)}% missing values.`);if(formulaErrors)insights.push(`${formulaErrors} formula/error cells were detected.`);return{name,rows:g.length,columns:w,headerRow:hr+1,rowCount:rows.length,fields,numericFields:numeric.map(f=>f.name),categoryFields:cat.map(f=>f.name),dateFields:dates.map(f=>f.name),formulaCount:formulas,formulaErrors,insights,referenceSheet:isRef,charts:cat.slice(0,4).map(f=>({type:"bar",dimension:f.name,data:f.topValues})),analytics:{crossTabs:cross(rows,fields),numericRelations:numericRelations(rows,fields),quality:quality(rows,fields)},cohort:isRef?null:cohortMetrics(rows,fields)}}
export async function analyzeWorkbook(file,onProgress=()=>{}){const wb=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true,cellFormula:true,cellNF:true,cellText:true}),sheets=[];for(let i=0;i<wb.SheetNames.length;i++){const name=wb.SheetNames[i];onProgress({current:i+1,total:wb.SheetNames.length,name});sheets.push(analyzeSheet(name,wb.Sheets[name]));await new Promise(r=>setTimeout(r,0))}const all=sheets.flatMap(s=>s.fields.map(f=>({...f,sheet:s.name}))),totalRows=sheets.reduce((a,s)=>a+s.rowCount,0),totalCols=sheets.reduce((a,s)=>a+s.columns,0),missing=all.reduce((a,f)=>a+f.missing,0),cells=sheets.reduce((a,s)=>a+s.rowCount*s.columns,0)||1,cohortSheet=sheets.find(s=>s.name.toLowerCase()==="register"&&s.cohort)||sheets.find(s=>s.cohort&&s.rowCount>=100)||sheets.find(s=>s.cohort)||null,cohorts=sheets.filter(s=>s.cohort).map(s=>({sheet:s.name,...s.cohort})),primary=cohortSheet?.cohort||null;return{fileName:file.name,fileSize:file.size,sheets,cohort:primary,cohorts,totals:{sheets:sheets.length,rows:totalRows,columns:totalCols,fields:all.length,missing,missingPct:missing/cells*100,formulaErrors:sheets.reduce((a,s)=>a+s.formulaErrors,0)},topFields:all.filter(f=>f.type!=="empty").sort((a,b)=>b.nonEmpty-a.nonEmpty).slice(0,30),workbookAnalytics:{quality:{duplicateRows:sheets.reduce((a,s)=>a+(s.analytics.quality?.duplicateRows||0),0),outliers:sheets.flatMap(s=>s.analytics.quality?.outliers||[])},crossTabs:sheets.flatMap(s=>(s.analytics.crossTabs||[]).map(x=>({...x,sheet:s.name}))),numericRelations:sheets.flatMap(s=>(s.analytics.numericRelations||[]).map(x=>({...x,sheet:s.name})))}}}
export function workbookInsights(m){const out=[],largest=[...m.sheets].sort((a,b)=>b.rowCount-a.rowCount)[0];if(largest)out.push(`${largest.name} is the largest sheet with ${largest.rowCount.toLocaleString()} populated records.`);out.push(`${m.totals.sheets} worksheets, ${m.totals.fields.toLocaleString()} fields and ${m.totals.rows.toLocaleString()} populated records were scanned.`);if(m.cohort){out.push(`Cohort intelligence identified ${m.cohort.recordCount.toLocaleString()} cohort records from ${m.cohort.nameField||"the detected client-name field"}.`);if(m.cohort.hiv?.tested)out.push(`${m.cohort.hiv.tested.toLocaleString()} clients have an interpretable HIV test result; positivity is ${m.cohort.hiv.positivityPct.toFixed(1)}%.`);if(m.cohort.due?.length)out.push(`${m.cohort.due.length.toLocaleString()} clients have an appointment or ARV/ART refill date overdue or within 30 days.`)}if(m.workbookAnalytics.quality.duplicateRows)out.push(`${m.workbookAnalytics.quality.duplicateRows.toLocaleString()} duplicate rows were detected.`);if(m.workbookAnalytics.numericRelations.length){const r=m.workbookAnalytics.numericRelations[0];out.push(`Strongest numeric relationship: ${r.x} vs ${r.y} (correlation ${r.correlation}).`)}out.push(`${m.totals.missingPct.toFixed(1)}% of analyzed cells are blank or marked missing.`);return out.slice(0,8)}
export{num,date,roleFor};